const ROLE_PERMISSIONS = {
    BE: ["CREATE_REQUEST"],
    BH: ["CREATE_REQUEST"],
    BL: ["CREATE_REQUEST"],
    BM: ["CREATE_REQUEST", "VIEW_MONTHLY_REPORT"],
    "Asst General Manager": ["CREATE_REQUEST", "VIEW_MONTHLY_REPORT", "VIEW_PLANNED_VISITS"],
    "Associate Vice President": ["CREATE_REQUEST", "VIEW_MONTHLY_REPORT", "VIEW_PLANNED_VISITS"],
    SBUH: ["CREATE_REQUEST"],
    TE: ["CREATE_REQUEST"],
    KAE: ["CREATE_REQUEST"],
    NE: ["CREATE_REQUEST"],

    MSL: ["VIEW_PLANNED_VISITS"],
    "Scientific Officer": ["VIEW_PLANNED_VISITS"],
    Admin: ["CREATE_REQUEST", "VIEW_MONTHLY_REPORT", "VIEW_PLANNED_VISITS"],
    admin: ["CREATE_REQUEST", "VIEW_MONTHLY_REPORT", "VIEW_PLANNED_VISITS"]
};

export { ROLE_PERMISSIONS };